### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by alxjsn** [moulco/moul#13] opened 2020-11-03 01:15 UTC
I currently get the following error when running the latest binary:

```
■ Starting dev server... ⠴ panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xa934ef]

goroutine 1 [running]:
github.com/moulco/moul/internal.GetPhotos.func1(0xc00056d620, 0x1e, 0x0, 0x0, 0xf167e0, 0xc0003fa8a0, 0xc00056d620, 0x1e)
	/Users/sophearak/Codes/moul/cli/internal/resize.go:101 +0x2f
path/filepath.Walk(0xc00056d620, 0x1e, 0xc0001159e8, 0xc000115a10, 0x50b5ab)
	/usr/local/Cellar/go/1.15/libexec/src/path/filepath/path.go:404 +0x6b
github.com/moulco/moul/internal.GetPhotos(0xc00056d620, 0x1e, 0x3, 0xc00056d620, 0x1e)
	/Users/sophearak/Codes/moul/cli/internal/resize.go:100 +0x6f
github.com/moulco/moul/cmd.getTemplate(0xc0000ca360, 0xc000036104, 0x11, 0xc87e80, 0xc0003fa150)
	/Users/sophearak/Codes/moul/cli/cmd/root.go:97 +0x15d
github.com/moulco/moul/cmd.previewFunc(0xc0002e6000, 0x1556f78, 0x0, 0x0)
	/Users/sophearak/Codes/moul/cli/cmd/root.go:181 +0x5e5
github.com/moulco/moul/cmd.Execute.func1(0xc0002e6000, 0x1556f78, 0x0, 0x0)
	/Users/sophearak/Codes/moul/cli/cmd/root.go:211 +0x49
github.com/spf13/cobra.(*Command).execute(0xc0002e6000, 0xc0000961e0, 0x0, 0x0, 0xc0002e6000, 0xc0000961e0)
	/Users/sophearak/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xc0002e6000, 0xc0001d1f50, 0x1, 0x1)
	/Users/sophearak/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/sophearak/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
github.com/moulco/moul/cmd.Execute()
	/Users/sophearak/Codes/moul/cli/cmd/root.go:230 +0x273
main.main()
	/Users/sophearak/Codes/moul/cli/main.go:8 +0x25
```

**Comment by alxjsn** [comment] 2020-11-03 01:22
Just as a note: I am running this on Arch Linux and have tried building multiple tagged from earlier and I get similar crashes.

**Comment by sophearak** [comment] 2020-11-03 12:36
👋  @alxjsn Can you help run `tree` in your generated folder? (Within directory where you have `moul.toml`)

I couldn't reproduce on `Linux archlinux 5.9.2-arch1-1 #1 SMP PREEMPT Thu, 29 Oct 2020 17:01:28 +0000 x86_64 GNU/Linux` (Arch Linux in Vagrant)

**Comment by alxjsn** [comment] 2020-11-11 01:37
Sorry for the late response. I figured it out. I originally used the example configuration in an empty directory and tried to run the command. It wasn't clear to me that I have to create a collection first. Maybe this should be made more clear through the error messages/documentation?

**Comment by sophearak** [comment] 2020-11-11 13:43
Ah, I see. Yeah, I totally agree. It should have covered that. Will work on it this weekend.

**Comment by sophearak** [comment] 2020-11-14 03:15
The fix for this is out https://github.com/moulco/moul/releases/tag/3.2.3

**Closed by sophearak** 2020-11-14 03:15 UTC
